# ==============================================================================
# Sistema Base y Logs
# ==============================================================================
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
CONFIG_LOG_BUFFER_SIZE=4096

# ==============================================================================
# Networking (Capa de Red Base)
# ==============================================================================
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y

# ==============================================================================
# Gestión de Red y Cliente DHCP (Para obtener IP de "TEDDY")
# ==============================================================================
CONFIG_NET_DHCPV4=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y

# ==============================================================================
# Dependencias del Servidor HTTP
# ==============================================================================
CONFIG_HTTP_PARSER=y
CONFIG_HTTP_PARSER_URL=y
CONFIG_EVENTFD=y
CONFIG_POSIX_API=y

# ==============================================================================
# TASK 1 - Capacidades del Laboratorio (IoT)
# ==============================================================================
CONFIG_WIFI=y
CONFIG_HTTP_SERVER=y
CONFIG_JSON_LIBRARY=y
CONFIG_LED_STRIP=y

# ==============================================================================
# Credenciales de la Red Wi-Fi
# ==============================================================================
CONFIG_LAB_WIFI_SSID="teddy-nitro"
CONFIG_LAB_WIFI_PSK="12345678"

# ==============================================================================
# Búferes de Red (Evita que los paquetes DHCP se descarten por falta de RAM)

# Aumentar tamaño de memoria para soportar navegadores web (Chrome/Safari)
# ==============================================================================
CONFIG_NET_BUF_DATA_SIZE=256
CONFIG_NET_BUF_RX_COUNT=64
CONFIG_NET_BUF_TX_COUNT=64
CONFIG_NET_PKT_RX_COUNT=32
CONFIG_NET_PKT_TX_COUNT=32




# Aumentar la capacidad de lectura del servidor HTTP
CONFIG_HTTP_SERVER_MAX_URL_LENGTH=128